[config]
autoboot=0
autoboot_list=0
bootwait=3
noticker=0
backlight=100
autohosoff=1
autonogc=1
updater2p=1
bootprotect=0

# Only include above what you want to change from defaults.
# config.c in bootloader and Nyx have all the defaults.






{------- Tools -------}
[Lockpick RCM]
payload=bootloader/payloads/Lockpick_RCM_Pro.bin



# hekate - CTCaer mod v5.8.0 .ini template
#
# All entries in this template can have these stylistic keys:
#  like logopath= key which is for bootlogo and icon= key for Nyx icon.
# Other than these, there many other keys to choose from, like the exosphere configuration keys.
# All of them are descibed in the main README.
#
# You can disable a key in a boot entry by using ; in front of it
#  Do not use # because that will break it.
#
# Do not use newline between keys or spaces before and after a key name/var.
# That will break the boot entry of config entry.
#
# NOT TO BE USED AS IS!
#  Pick [config] and then only the needed [sections]. # or { } lines can be ommited.
#  If [config] is not copied, hekate will create one with defaults.
#  If wanted, only the changed [config] defaults can be set. The rest will be created automatically.
#
# Note: The keys in a section are parsed sequentially.
#  This is important for override order of keys (if any double or matching functionality).

# Disclaimer: There are many combos, that allow hekate to basically boot everything NATIVELY.
#  hekate will ALWAYS do what YOU tell it to do. If you get an error,
#  that means that hekate_ipl.ini was wrongly made or files are missing/corrupt/etc!
